# Generated by Django 5.0.6 on 2024-05-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.IntegerField()),
                ("room_type", models.CharField(max_length=100)),
                ("room_price", models.IntegerField()),
                ("room_status", models.CharField(max_length=100)),
                ("room_description", models.TextField()),
                ("room_image", models.ImageField(upload_to="images/")),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(max_length=100)),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("total_price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.IntegerField()),
                ("room_type", models.CharField(max_length=100)),
                ("room_price", models.IntegerField()),
                ("room_status", models.CharField(max_length=100)),
                ("room_description", models.TextField()),
                ("room_image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
